import { atom } from "recoil";

export const ManagementAtom = atom({
  key: "managementState",
  default: [
    {
      id: 1,
      inventoryStatus: 'Current',
      inventoryLevel: 150,
      productName: 'Product 1',
      productDescription: 'Description for Product 1',
      price: 29.99,
      stockLevel: 100,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 2,
      inventoryStatus: 'Out of Stock',
      inventoryLevel: 0,
      productName: 'Product 2',
      productDescription: 'Description for Product 2',
      price: 49.99,
      stockLevel: 50,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 3,
      inventoryStatus: 'Current',
      inventoryLevel: 25,
      productName: 'Product 3',
      productDescription: 'Description for Product 3',
      price: 39.99,
      stockLevel: 75,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 4,
      inventoryStatus: 'Current',
      inventoryLevel: 30,
      productName: 'Product 4',
      productDescription: 'Description for Product 4',
      price: 19.99,
      stockLevel: 120,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 5,
      inventoryStatus: 'Current',
      inventoryLevel: 0,
      productName: 'Product 5',
      productDescription: 'Description for Product 5',
      price: 59.99,
      stockLevel: 60,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 6,
      inventoryStatus: 'Current',
      inventoryLevel: 15,
      productName: 'Product 6',
      productDescription: 'Description for Product 6',
      price: 34.99,
      stockLevel: 80,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 7,
      inventoryStatus: 'Current',
      inventoryLevel: 40,
      productName: 'Product 7',
      productDescription: 'Description for Product 7',
      price: 25.99,
      stockLevel: 95,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 8,
      inventoryStatus: 'Out of Stock',
      inventoryLevel: 0,
      productName: 'Product 8',
      productDescription: 'Description for Product 8',
      price: 44.99,
      stockLevel: 70,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 9,
      inventoryStatus: 'Current',
      inventoryLevel: 20,
      productName: 'Product 9',
      productDescription: 'Description for Product 9',
      price: 31.99,
      stockLevel: 110,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 10,
      inventoryStatus: 'Current',
      inventoryLevel: 35,
      productName: 'Product 10',
      productDescription: 'Description for Product 10',
      price: 27.99,
      stockLevel: 130,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 11,
      inventoryStatus: 'Current',
      inventoryLevel: 45,
      productName: 'Product 11',
      productDescription: 'Description for Product 11',
      price: 23.99,
      stockLevel: 85,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 12,
      inventoryStatus: 'Out of Stock',
      inventoryLevel: 0,
      productName: 'Product 12',
      productDescription: 'Description for Product 12',
      price: 55.99,
      stockLevel: 55,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 13,
      inventoryStatus: 'Current',
      inventoryLevel: 28,
      productName: 'Product 13',
      productDescription: 'Description for Product 13',
      price: 36.99,
      stockLevel: 90,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 14,
      inventoryStatus: 'Current',
      inventoryLevel: 42,
      productName: 'Product 14',
      productDescription: 'Description for Product 14',
      price: 21.99,
      stockLevel: 105,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 15,
      inventoryStatus: 'Out of Stock',
      inventoryLevel: 0,
      productName: 'Product 15',
      productDescription: 'Description for Product 15',
      price: 47.99,
      stockLevel: 65,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 16,
      inventoryStatus: 'Current',
      inventoryLevel: 22,
      productName: 'Product 16',
      productDescription: 'Description for Product 16',
      price: 32.99,
      stockLevel: 115,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 17,
      inventoryStatus: 'Current',
      inventoryLevel: 38,
      productName: 'Product 17',
      productDescription: 'Description for Product 17',
      price: 28.99,
      stockLevel: 140,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 18,
      inventoryStatus: 'Current',
      inventoryLevel: 48,
      productName: 'Product 18',
      productDescription: 'Description for Product 18',
      price: 24.99,
      stockLevel: 75,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 19,
      inventoryStatus: 'Out of Stock',
      inventoryLevel: 0,
      productName: 'Product 19',
      productDescription: 'Description for Product 19',
      price: 54.99,
      stockLevel: 50,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
    {
      id: 20,
      inventoryStatus: 'Current',
      inventoryLevel: 18,
      productName: 'Product 20',
      productDescription: 'Description for Product 20',
      price: 37.99,
      stockLevel: 95,
      image: 'https://www.swampscottlibrary.org/wp-content/uploads/logo.gif',
    },
  ]
  
  
});